#include <iostream>
#include <math.h>
#include <map>
#include <tuple> 
#include <fstream>
#include <cstdlib>
using namespace std;
typedef unsigned int int64;
typedef map<int64,tuple<double,double>> estructura;
void generarPdf(int64 iter,int64 maxIter,estructura tabla,double err);
double f(double x)
{
	return pow(x,2)-2;
}

/*
La siguiente función es la implementacion del método de la secante
parámetro: f,df,p0,delta,epsilon,maxIter
f es una función
df, es la derivada de la función f
po, es la aproximacin inicial a un 0 de f
delta, es la tolerancia para p0
epsilon, es la tolerancia para los valores de la funcin
maxIter, máximo número de iteraciones.
*/
double metodoSecante(double (f)(double),double p0,double p1,double delta,double epsilon,int64 maxIter)
{
	double err=0;//estimacion del error de p0
	double p2=0;//punto siguiente a tomar
	double y=f(p0);//valor de la funcion
	double relerr=0;//error relativo
	int64 i=0;
	estructura tabla;
	while(i<maxIter)
	{
		tabla[i]=tuple<double,double>(p1,f(p0));
		p2=p1-f(p1)*(p1-p0)/(f(p1)-f(p0));
		err=fabs(p2-p1);
		relerr=2*err/(fabs(p1)+delta);
		p0=p1;
		p1=p2;
		y=f(p1);
		if(err<delta||relerr<delta||fabs(y)<epsilon) break;
		i++;
	}	
	
	generarPdf(i,maxIter,tabla,err);
	return p0;
}	

void generarPdf(int64 iter,int64 maxIter,estructura tabla,double err)
{
	string FileName="metodoSecante.tex";
	ofstream salida(FileName.c_str());
	salida<<"\\documentclass[a4paper,10pt]{article}"<<endl;
	salida<<"\\usepackage[utf8]{inputenc}"<<endl;
	salida<<"\\title{}"<<endl;
	salida<<"\\author{Table generated by R\\'omulo Walter Condori Bustincio}"<<endl;
	salida<<"\\begin{document}"<<endl;
	salida<<"\\maketitle"<<endl;
	salida<<"Con un total de "<<iter<<" de "<<maxIter<<" iteraciones permitidas, se obtuvo la siguiente tabla:"<<endl; 
	salida<<"\\begin{center}"<<endl;
	salida<<"\\begin{tabular}{|c|c|c|}"<<endl;
	salida<<"\\hline"<<endl;
	salida<<"Iteraci\\'on&$r$&$f(r)$\\\\"<<endl;
	salida<<"\\hline"<<endl;
	///Conseguir datos
	estructura::iterator it;
	for(it=tabla.begin();it!=tabla.end();it++)
	{
		salida<<(*it).first<<"&"<<get<0>((*it).second)<<"&"<<get<1>((*it).second)<<"\\\\"<<endl;
	}	
	it--;
	salida<<"\\hline"<<endl;
	salida<<"\\end{tabular}"<<endl;
	salida<<"\\end{center}"<<endl;
	salida<<"Donde el valor de $r$ aproximado es "<<get<0>((*it).second);
	salida<<" con un error relativo de: "<<err<<endl;
	salida<<"\\end{document}"<<endl;
	
	string comand="pdflatex "+FileName;
	system(comand.c_str());
}	
int main()
{
	metodoSecante(f,1,2,0.000001,0.000001,100);
	//newtonRaphsonver1(fun2,dfun2,7,0.00001,0.00001,100000);
	//newtonRaphsonver2(fun2,0.001,7,0.00001,0.00001,100000);
	//newtonRaphsonver1(fun1,dfun1,7,0.00001,0.00001,100000);
	//newtonRaphsonver2(fun1,0.001,7,0.00001,0.00001,100000);
	return 0;
}

